### ISSUE TITLE
Implement Scoring system

### ISSUE THREAD

**Issue by gachia** [Lightcaster-Studios/Beamerman#172]
In addition to the current lives system, secondary ranking will be determined by a scoring system.

This aims to add another level of depth and satisfaction to the game, by rewarding players for executing high-risk, high-reward actions.

Sources of Score:
- Alive players passively gain score
- Players gain score through interactions with the environment (such as from Point Beacons)
- Players gain score by picking up certain power-ups
- Alive players steal a percentage of the score from players they kill with their lazer
- Dead players steal a smaller percentage of the score from players they kill with spawned obstacles
- Players killed from environmental hazards lose the same amount of points as if killed by an alive player, but the points are spread across all living players

**Comment by iskandarzulkarnaien** [comment]
PR #182 implements most of the core mechanics of the score system. These pointers are to be addressed in a separate PR:

Todos:
- Die not due to other player's actions, steal score and distribute to all players
- Detect damage done by barrel and use that to calculate score too
- Detect object destroy and increment score (mainly for skyhook pillar)
- HUD element to show score increments

Bugs:
- Some Horizontal/Diagonal Mirrors do not trigger the score increase
- Hitting players with protective temporary powerups still grants score (e.g. TempArmor)

**Comment by gachia** [comment]
Closing this issue since #182 implements the core mechanics of the system. We will move the above issues into a new issue.
