### ISSUE TITLE
Create blog for marketing

### ISSUE THREAD

**Issue by gachia** [Lightcaster-Studios/Beamerman#177]
Create blog with marketing materials

**Comment by raniceyue** [comment]
Hi, with regards to the blog, we already have one under our organisation, you can work on that one! It uses the jekyll static site generator (templating language in Ruby), with Bulma CSS. Right now it's sort of in shambles because I didn't have time to work on the website.

I used somebody else's theme as the base theme of the site. If you want to change the theme, you can make a PR and just refactor the whole thing.

**Comment by gachia** [comment]
Noted. I've edited the website to include a blog section and have added two blog posts to get started. Closing Issue now.
